color_range_list:
  black:
    max:
    - 56
    - 255
    - 255
    min:
    - 0
    - 0
    - 0
  blue:
    max:
    - 255
    - 255
    - 113
    min:
    - 0
    - 0
    - 0
  green:
    max:
    - 116
    - 119
    - 154
    min:
    - 0
    - 0
    - 83
  red:
    max:
    - 104
    - 255
    - 169
    min:
    - 0
    - 139
    - 131
  white:
    max:
    - 255
    - 255
    - 255
    min:
    - 76
    - 3
    - 0
